"""Vista principal de la pestaña Presupuestos."""

from __future__ import annotations

from typing import TYPE_CHECKING

from PyQt6.QtCore import QDate, Qt
from PyQt6.QtWidgets import (
    QFrame,
    QGridLayout,
    QGroupBox,
    QHeaderView,
    QHBoxLayout,
    QLabel,
    QVBoxLayout,
    QWidget,
)

from pos_uniformes.ui.helpers.date_field_helper import configure_friendly_date_edit

if TYPE_CHECKING:
    from pos_uniformes.ui.main_window import MainWindow


def build_quotes_tab(window: "MainWindow") -> QWidget:
    widget = QWidget()
    layout = QVBoxLayout()
    layout.setSpacing(8)

    quote_box = QGroupBox("Presupuesto actual")
    quote_box.setObjectName("infoCard")
    quote_layout = QVBoxLayout()
    quote_layout.setSpacing(8)
    window.quote_sku_input.setPlaceholderText("Escanea o captura el SKU")
    window.quote_sku_input.setClearButtonEnabled(True)
    window.quote_sku_input.setMinimumWidth(280)
    window.quote_folio_input.setObjectName("readOnlyField")
    window.quote_client_combo.setObjectName("toolbarSelect")
    window.quote_create_client_button.setObjectName("toolbarGhostButton")
    configure_friendly_date_edit(window.quote_validity_input, initial_date=QDate.currentDate().addDays(7))
    window.quote_note_input.setMaximumHeight(90)
    window.quote_note_input.setPlaceholderText("Observaciones adicionales")
    window.quote_add_button.setObjectName("toolbarSecondaryButton")
    window.quote_save_button.setText("Emitir presupuesto")
    window.quote_save_button.setObjectName("toolbarPrimaryButton")
    window.quote_qty_down_button.setObjectName("toolbarGhostButton")
    window.quote_qty_up_button.setObjectName("toolbarGhostButton")
    window.quote_remove_button.setObjectName("toolbarSecondaryButton")
    window.quote_clear_button.setObjectName("toolbarGhostButton")
    window.quote_cancel_button.setObjectName("cashierDangerButton")
    window.quote_whatsapp_button.setObjectName("toolbarGhostButton")
    window.quote_refresh_button.setObjectName("toolbarGhostButton")
    window.quote_total_label.setObjectName("cashierTotalValue")
    window.quote_total_meta_label.setObjectName("cashierMetaLabel")
    window.quote_summary_label.setObjectName("cashierSummaryCard")
    window.quote_status_label.setObjectName("subtleLine")

    def form_label(text: str) -> QLabel:
        label = QLabel(text)
        label.setObjectName("cashierMetaLabel")
        return label

    scan_stack = QVBoxLayout()
    scan_stack.setSpacing(4)
    scan_stack.addWidget(form_label("Escaneo"))

    scan_row = QHBoxLayout()
    scan_row.setSpacing(8)
    scan_row.addWidget(window.quote_sku_input, 1)
    scan_row.addWidget(window.quote_add_button)
    scan_row.addStretch(2)
    scan_stack.addLayout(scan_row)

    quote_form = QGridLayout()
    quote_form.setHorizontalSpacing(10)
    quote_form.setVerticalSpacing(8)
    quote_form.addWidget(form_label("Folio"), 0, 0)
    quote_form.addWidget(window.quote_folio_input, 0, 1, 1, 2)
    quote_form.addWidget(form_label("Cliente asignado"), 0, 3)
    quote_form.addWidget(window.quote_client_combo, 0, 4, 1, 2)
    quote_form.addWidget(window.quote_create_client_button, 0, 6)
    quote_form.addWidget(form_label("Vigencia"), 1, 0)
    quote_form.addWidget(window.quote_validity_input, 1, 1, 1, 2)
    quote_form.addWidget(form_label("Observacion"), 2, 0)
    quote_form.addWidget(window.quote_note_input, 2, 1, 1, 6)
    quote_form.setColumnStretch(1, 1)
    quote_form.setColumnStretch(4, 1)

    quote_actions = QHBoxLayout()
    quote_actions.setSpacing(6)
    quote_actions.addWidget(window.quote_save_button)
    quote_actions.addStretch()
    quote_actions.addWidget(window.quote_qty_down_button)
    quote_actions.addWidget(window.quote_qty_up_button)
    quote_actions.addWidget(window.quote_remove_button)
    quote_actions.addWidget(window.quote_clear_button)

    window.quote_cart_table.setColumnCount(5)
    window.quote_cart_table.setHorizontalHeaderLabels(["SKU", "Producto", "Cantidad", "Precio", "Subtotal"])
    window.quote_cart_table.setObjectName("dataTable")
    window.quote_cart_table.verticalHeader().setVisible(False)
    window.quote_cart_table.setSelectionBehavior(window.quote_cart_table.SelectionBehavior.SelectRows)
    window.quote_cart_table.setAlternatingRowColors(True)
    window.quote_cart_table.setMinimumHeight(180)

    totals_box = QFrame()
    totals_box.setObjectName("cashierTotalsCard")
    totals_layout = QVBoxLayout()
    totals_layout.setContentsMargins(12, 10, 12, 10)
    totals_layout.setSpacing(2)
    totals_layout.addWidget(window.quote_total_meta_label)
    totals_layout.addWidget(window.quote_total_label)
    totals_box.setLayout(totals_layout)

    quote_top = QHBoxLayout()
    quote_top.setSpacing(10)
    quote_editor_column = QVBoxLayout()
    quote_editor_column.setSpacing(8)
    quote_editor_column.addLayout(scan_stack)
    quote_editor_column.addLayout(quote_form)
    quote_top.addLayout(quote_editor_column, 1)
    quote_top.addWidget(totals_box, 0, Qt.AlignmentFlag.AlignTop)

    quote_layout.addLayout(quote_top)
    quote_layout.addLayout(quote_actions)
    quote_layout.addWidget(window.quote_cart_table)
    quote_layout.addWidget(window.quote_summary_label)
    quote_box.setLayout(quote_layout)

    quote_cart_header = window.quote_cart_table.horizontalHeader()
    quote_cart_header.setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    quote_cart_header.setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    quote_cart_header.setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    quote_cart_header.setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    quote_cart_header.setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    quote_cart_header.setStretchLastSection(False)

    history_box = QGroupBox("Presupuestos recientes")
    history_box.setObjectName("infoCard")
    history_layout = QVBoxLayout()
    history_layout.setSpacing(8)
    filters_row = QHBoxLayout()
    filters_row.setSpacing(6)
    actions_row = QHBoxLayout()
    actions_row.setSpacing(6)
    window.quote_search_input.setPlaceholderText("Buscar por folio, cliente, telefono o SKU")
    window.quote_search_input.setClearButtonEnabled(True)
    window.quote_state_combo.setObjectName("inventoryFilterCombo")
    window.quote_state_combo.clear()
    window.quote_state_combo.addItem("Estado: todos", "")
    window.quote_state_combo.addItem("Emitidos", "EMITIDO")
    window.quote_state_combo.addItem("Borradores", "BORRADOR")
    window.quote_state_combo.addItem("Cancelados", "CANCELADO")
    window.quote_state_combo.addItem("Convertidos", "CONVERTIDO")
    window.quote_whatsapp_button.setText("Compartir por WhatsApp")
    filters_row.addWidget(window.quote_search_input, 1)
    filters_row.addWidget(window.quote_state_combo)
    filters_row.addWidget(window.quote_refresh_button)

    actions_row.addStretch()
    actions_row.addWidget(window.quote_whatsapp_button)
    actions_row.addWidget(window.quote_cancel_button)

    window.quote_table.setColumnCount(7)
    window.quote_table.setHorizontalHeaderLabels(
        ["Folio", "Cliente", "Estado", "Total", "Usuario", "Vigencia", "Fecha"]
    )
    window.quote_table.setObjectName("dataTable")
    window.quote_table.verticalHeader().setVisible(False)
    window.quote_table.setSelectionBehavior(window.quote_table.SelectionBehavior.SelectRows)
    window.quote_table.setAlternatingRowColors(True)
    window.quote_table.setMinimumHeight(220)
    window.quote_table.itemSelectionChanged.connect(window._handle_quote_selection)
    quote_table_header = window.quote_table.horizontalHeader()
    quote_table_header.setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    quote_table_header.setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    quote_table_header.setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    quote_table_header.setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    quote_table_header.setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    quote_table_header.setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    quote_table_header.setSectionResizeMode(6, QHeaderView.ResizeMode.ResizeToContents)
    quote_table_header.setStretchLastSection(False)

    detail_box = QGroupBox("Detalle seleccionado")
    detail_box.setObjectName("infoCard")
    detail_layout = QVBoxLayout()
    detail_layout.setSpacing(8)
    window.quote_customer_label.setObjectName("quoteDetailTitle")
    window.quote_meta_label.setWordWrap(True)
    window.quote_meta_label.setObjectName("quoteDetailMetaText")
    window.quote_notes_label.setWordWrap(True)
    window.quote_notes_label.setObjectName("quoteDetailNotesText")
    window.quote_detail_table.setColumnCount(5)
    window.quote_detail_table.setHorizontalHeaderLabels(["SKU", "Producto", "Cantidad", "Precio", "Subtotal"])
    window.quote_detail_table.setObjectName("dataTable")
    window.quote_detail_table.verticalHeader().setVisible(False)
    window.quote_detail_table.setSelectionBehavior(window.quote_detail_table.SelectionBehavior.SelectRows)
    window.quote_detail_table.setAlternatingRowColors(True)
    window.quote_detail_table.setMinimumHeight(240)
    quote_detail_header = window.quote_detail_table.horizontalHeader()
    quote_detail_header.setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    quote_detail_header.setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    quote_detail_header.setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    quote_detail_header.setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    quote_detail_header.setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    quote_detail_header.setStretchLastSection(False)

    detail_meta_card = QFrame()
    detail_meta_card.setObjectName("quoteDetailCard")
    detail_meta_layout = QVBoxLayout()
    detail_meta_layout.setContentsMargins(12, 10, 12, 10)
    detail_meta_layout.setSpacing(6)
    detail_meta_layout.addWidget(window.quote_meta_label)
    detail_meta_card.setLayout(detail_meta_layout)

    detail_notes_card = QFrame()
    detail_notes_card.setObjectName("quoteDetailCard")
    detail_notes_layout = QVBoxLayout()
    detail_notes_layout.setContentsMargins(12, 10, 12, 10)
    detail_notes_layout.setSpacing(6)
    detail_notes_layout.addWidget(window.quote_notes_label)
    detail_notes_card.setLayout(detail_notes_layout)

    detail_layout.addWidget(window.quote_customer_label)
    detail_layout.addWidget(detail_meta_card)
    detail_layout.addWidget(detail_notes_card)
    detail_layout.addWidget(window.quote_detail_table)
    detail_box.setLayout(detail_layout)

    history_layout.addWidget(window.quote_status_label)
    history_layout.addLayout(filters_row)
    history_layout.addLayout(actions_row)
    history_content = QHBoxLayout()
    history_content.setSpacing(10)
    history_content.addWidget(window.quote_table, 3)
    history_content.addWidget(detail_box, 2)
    history_layout.addLayout(history_content)
    history_box.setLayout(history_layout)

    layout.addWidget(quote_box)
    layout.addWidget(history_box, 1)

    window.quote_add_button.clicked.connect(window._handle_add_quote_item)
    window.quote_sku_input.returnPressed.connect(window._handle_add_quote_item)
    window.quote_save_button.clicked.connect(window._handle_save_quote)
    window.quote_qty_down_button.clicked.connect(window._handle_decrease_quote_item_quantity)
    window.quote_qty_up_button.clicked.connect(window._handle_increase_quote_item_quantity)
    window.quote_remove_button.clicked.connect(window._handle_remove_quote_item)
    window.quote_clear_button.clicked.connect(window._handle_clear_quote_cart)
    window.quote_refresh_button.clicked.connect(window._handle_quote_filters_changed)
    window.quote_whatsapp_button.clicked.connect(window._handle_open_quote_whatsapp)
    window.quote_cancel_button.clicked.connect(window._handle_cancel_quote)
    window.quote_create_client_button.clicked.connect(window._handle_create_quote_client)
    window.quote_search_input.textChanged.connect(window._handle_quote_filters_changed)
    window.quote_state_combo.currentIndexChanged.connect(window._handle_quote_filters_changed)

    window._reset_quote_form()
    window._refresh_quote_cart_table()
    widget.setLayout(layout)
    return widget
