"""add sales purchases users suppliers"""

revision = '0c8caec32b78'
down_revision = '3943a4b045d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedor'))
    )
    op.create_index(op.f('ix_proveedor_nombre'), 'proveedor', ['nombre'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'CAJERO', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'CONFIRMADA', 'CANCELADA', name='estado_compra'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('confirmada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_compra_proveedor_id_proveedor'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_compra_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra'))
    )
    op.create_index(op.f('ix_compra_estado'), 'compra', ['estado'], unique=False)
    op.create_index(op.f('ix_compra_numero_documento'), 'compra', ['numero_documento'], unique=True)
    op.create_index(op.f('ix_compra_proveedor_id'), 'compra', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_compra_usuario_id'), 'compra', ['usuario_id'], unique=False)
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cancelado_por_id', sa.Integer(), nullable=True),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'CONFIRMADA', 'CANCELADA', name='estado_venta'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('confirmada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['usuario.id'], name=op.f('fk_venta_cancelado_por_id_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_venta_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta'))
    )
    op.create_index(op.f('ix_venta_cancelado_por_id'), 'venta', ['cancelado_por_id'], unique=False)
    op.create_index(op.f('ix_venta_estado'), 'venta', ['estado'], unique=False)
    op.create_index(op.f('ix_venta_folio'), 'venta', ['folio'], unique=True)
    op.create_index(op.f('ix_venta_usuario_id'), 'venta', ['usuario_id'], unique=False)
    op.create_table('compra_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_compra_detalle_compra_detalle_cantidad_positiva')),
    sa.CheckConstraint('costo_unitario >= 0', name=op.f('ck_compra_detalle_compra_detalle_costo_unitario_no_negativo')),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_compra_detalle_compra_id_compra'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], name=op.f('fk_compra_detalle_variante_id_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra_detalle')),
    sa.UniqueConstraint('compra_id', 'variante_id', name='compra_detalle_variante_unica')
    )
    op.create_index(op.f('ix_compra_detalle_compra_id'), 'compra_detalle', ['compra_id'], unique=False)
    op.create_index(op.f('ix_compra_detalle_variante_id'), 'compra_detalle', ['variante_id'], unique=False)
    op.create_table('venta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_venta_detalle_venta_detalle_cantidad_positiva')),
    sa.CheckConstraint('precio_unitario >= 0', name=op.f('ck_venta_detalle_venta_detalle_precio_unitario_no_negativo')),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], name=op.f('fk_venta_detalle_variante_id_variante'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_venta_detalle_venta_id_venta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_detalle')),
    sa.UniqueConstraint('venta_id', 'variante_id', name='venta_detalle_variante_unica')
    )
    op.create_index(op.f('ix_venta_detalle_variante_id'), 'venta_detalle', ['variante_id'], unique=False)
    op.create_index(op.f('ix_venta_detalle_venta_id'), 'venta_detalle', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_detalle_venta_id'), table_name='venta_detalle')
    op.drop_index(op.f('ix_venta_detalle_variante_id'), table_name='venta_detalle')
    op.drop_table('venta_detalle')
    op.drop_index(op.f('ix_compra_detalle_variante_id'), table_name='compra_detalle')
    op.drop_index(op.f('ix_compra_detalle_compra_id'), table_name='compra_detalle')
    op.drop_table('compra_detalle')
    op.drop_index(op.f('ix_venta_usuario_id'), table_name='venta')
    op.drop_index(op.f('ix_venta_folio'), table_name='venta')
    op.drop_index(op.f('ix_venta_estado'), table_name='venta')
    op.drop_index(op.f('ix_venta_cancelado_por_id'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_compra_usuario_id'), table_name='compra')
    op.drop_index(op.f('ix_compra_proveedor_id'), table_name='compra')
    op.drop_index(op.f('ix_compra_numero_documento'), table_name='compra')
    op.drop_index(op.f('ix_compra_estado'), table_name='compra')
    op.drop_table('compra')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_proveedor_nombre'), table_name='proveedor')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
