"""initial schema"""

revision = '3943a4b045d6'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria'))
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=True)
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marca'))
    )
    op.create_index(op.f('ix_marca_nombre'), 'marca', ['nombre'], unique=True)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_producto_categoria_id_categoria'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], name=op.f('fk_producto_marca_id_marca'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto')),
    sa.UniqueConstraint('marca_id', 'nombre', name='producto_nombre_marca_unico')
    )
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=False)
    op.create_table('variante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('talla', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_referencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock_actual >= 0', name=op.f('ck_variante_variante_stock_actual_no_negativo')),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_variante_producto_id_producto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variante')),
    sa.UniqueConstraint('producto_id', 'talla', 'color', name='producto_talla_color_unico')
    )
    op.create_index(op.f('ix_variante_color'), 'variante', ['color'], unique=False)
    op.create_index(op.f('ix_variante_sku'), 'variante', ['sku'], unique=True)
    op.create_index(op.f('ix_variante_talla'), 'variante', ['talla'], unique=False)
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA_COMPRA', 'SALIDA_VENTA', 'AJUSTE_ENTRADA', 'AJUSTE_SALIDA', 'CANCELACION_VENTA', name='tipo_movimiento_inventario'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_posterior', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad <> 0', name=op.f('ck_movimiento_inventario_movimiento_inventario_cantidad_no_cero')),
    sa.CheckConstraint('stock_posterior >= 0', name=op.f('ck_movimiento_inventario_movimiento_inventario_stock_posterior_no_negativo')),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], name=op.f('fk_movimiento_inventario_variante_id_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_inventario'))
    )
    op.create_index(op.f('ix_movimiento_inventario_created_at'), 'movimiento_inventario', ['created_at'], unique=False)
    op.create_index(op.f('ix_movimiento_inventario_tipo_movimiento'), 'movimiento_inventario', ['tipo_movimiento'], unique=False)
    op.create_index(op.f('ix_movimiento_inventario_variante_id'), 'movimiento_inventario', ['variante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimiento_inventario_variante_id'), table_name='movimiento_inventario')
    op.drop_index(op.f('ix_movimiento_inventario_tipo_movimiento'), table_name='movimiento_inventario')
    op.drop_index(op.f('ix_movimiento_inventario_created_at'), table_name='movimiento_inventario')
    op.drop_table('movimiento_inventario')
    op.drop_index(op.f('ix_variante_talla'), table_name='variante')
    op.drop_index(op.f('ix_variante_sku'), table_name='variante')
    op.drop_index(op.f('ix_variante_color'), table_name='variante')
    op.drop_table('variante')
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_marca_nombre'), table_name='marca')
    op.drop_table('marca')
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
